
select 
	CustomerID,
	CPF_Cliente, 
	Nome_Cliente, 
	Nome_Mae, 
	Dt_Nascimento, 
	StatusConta, 
	End_Cliente, 
	BairroCliente, 
	Cidade_Cliente, 
	UF_Cliente, 
	Email, 
	DDD, 
	Telefone, 
	Dt_Abertura, 
	Safra_Abertura, 
	Flag_TempodeConta, 
	Flag_TempoBloqueado, 
	MotivoStatus, 
	sub_classification, 
	sub_classification_obs, 
	DataStatus, 
	UsuarioStatus, 
	ScoreZaig, 
	Flag_Biometria, 
	Flag_Funcionario, 
	Flag_Tetativas, 
	Flag_Bancos, 
	Flag_Card, 
	Flag_Ativo, 
	Flag_Perfil 
from `eai-datalake-data-sandbox.analytics_prevencao_fraude.tb_base_cliente_Perfil`
where MotivoStatus = 'Fraude confirmada' and DataStatus >= '2024-06-20'